### ISSUE TITLE
How to handle MODx advanced installation?

### ISSUE THREAD

**Issue by travisbotello** [modmore/GitifyWatch#4]
I am using MODx advanced installations with Gitify which is working very smoothly so far. Today I installed and configured Gitify Watch but I am having problems setting it up:

`[2018-01-09 17:03:51] (ERROR in mhwd\GitifyWatch::getEnvironment @ /Users/travisbotello/Projekte/modx/staging/core/components/gitifywatch/model/gitifywatch/gitifywatch.class.php : 156) Error loading environment configuration: Directory is not a Gitify directory: /Users/travisbotello/Projekte/modx/staging/public_html/`

`.gitify` file is not found in `public_html` folder so I had to duplicate it and move it from `root` to `public_html` folder which means I have to maintain two `.gitify` files.

Once this is done Gitify Watch correctly adds tasks to Scheduler. But when cronjob is run I am receiving the following error msg:

`"/Users/travisbotello/Projekte/modx/staging/public_html" is not a git repository`

This is correct because my `root` folder is the git repository and `public_html` is just a subfolder.

I don't know how to bypass this issue.

Any ideas?

**Comment by Mark-H** [comment]
There's a setting that let's you point GW to the repository root. That
should cover both the .gitify and git root.

Op 9 jan. 2018 6:45 p.m. schreef "Travis Botello" <notifications@github.com

**Comment by travisbotello** [comment]
Indeed there is a setting called `gitifywatch.repository_path` which I filled out with my repository root path:`/Users/travisbotello/Projekte/modx/staging/` 

But I am still receiving same error message when cron is running. When I debug `gitifywatch.class.php` I can see that it get's the correct setting's value and passes it as `array('repositoryPath')` to `$config` variable. The stack trace is:

```
PHP Fatal error:  Uncaught Error: Call to a member function add() on string in /Users/travisbotello/Projekte/modx/staging/core/components/gitifywatch/model/gitifywatch/gitifywatch.class.php:132
Stack trace:
#0 /Users/travisbotello/Projekte/modx/staging/core/components/gitifywatch/model/gitifywatch/gitifywatch.class.php(100): mhwd\GitifyWatch->commitAndPush('tmmanager edite...')
#1 /Users/travisbotello/Projekte/modx/staging/core/components/gitifywatch/elements/tasks/extract.task.php(89): mhwd\GitifyWatch->extract(Array, true, 'tmmanager edite...')
#2 /Users/travisbotello/Projekte/modx/staging/core/components/scheduler/model/scheduler/sfiletask.class.php(60): include('/Users/travisbo...')
#3 /Users/travisbotello/Projekte/modx/staging/core/components/scheduler/model/scheduler/stask.class.php(41): sFileTask->_run(Object(sTaskRun_mysql))
#4 /Users/travisbotello/Projekte/modx/staging/public_html/assets/components/scheduler/run.php(37): sTask->run(Object(sTaskRun_mysql))
#5 {main}
  thrown in /Users/travisbotello/Projekte/modx/staging/core/components/gitifywatch/model/gitifywatch/gitifywatch.class.php on line 132
```

 When I `print $repo` variable it outputs `"/Users/travisbotello/Projekte/modx/staging/public_html" is not a git repository`. So it looks like that `repositoryPath` that I set in settings is not passed to Gitify...

**Comment by travisbotello** [comment]
My bad...I used the wrong setting because the necessary one was not in MODx by default. I manually added `gitify.repository_path` my MODx installation:

`gitify.repository_path` => root path to your git repo (not in MODx by default)

vs.

`gitifywatch.repository_path` => root path to your gitify installation


This might be the same path but you have to add both settings to make it work. To me it was somehow confusing because I think gitifywatch and gitify have to use the same path to work, right? May I add three improvement suggestions:

1. Change `gitify.repository_path` to `gitifywatch.git_repository_path` to emphasize the difference between both settings.
2. Add `gitify.repository_path` setting to MODx by default when installing Gitify Watch. I had to observe the Gitify code to find this setting.
3. Implement an error condition in `gitifywatch.class.php` to test if `$repo` was loaded correctly. (Right now we are only testing for `!$repo` which can also be populated with a git error msg like in the above case). In my case I had to observe cron error log to identify the issue.

**Comment by travisbotello** [comment]
Added pull request for suggestion 3: https://github.com/modmore/GitifyWatch/pull/5
